export const FETCH_GARTENS_START = "GARTENS/FETCH_GARTENS_START"
export const FETCH_GARTENS_FAILURE = "GARTENS/FETCH_GARTENS_FAILURE"
export const FETCH_GARTENS_SUCCESS = "GARTENS/FETCH_GARTENS_SUCCESS"

export const FETCH_GARTEN_START = "GARTENS/FETCH_GARTEN_START"
export const FETCH_GARTEN_FAILURE = "GARTENS/FETCH_GARTEN_FAILURE"
export const FETCH_GARTEN_SUCCESS = "GARTENS/FETCH_GARTEN_SUCCESS"

export const FETCH_GROUPS_START = "GROUPS/FETCH_GROUPS_START"
export const FETCH_GROUPS_FAILURE = "GROUPS/FETCH_GROUPS_FAILURE"
export const FETCH_GROUPS_SUCCESS = "GROUPS/FETCH_GROUPS_SUCCESS"

// export const FETCH_GROUP_START = "GROUPS/FETCH_GROUP_START"
// export const FETCH_GROUP_FAILURE = "GROUPS/FETCH_GROUP_FAILURE"
// export const FETCH_GROUP_SUCCESS = "GROUPS/FETCH_GROUP_SUCCESS"

export const ADD_GROUP = "GROUPS/ADD_GROUP"

export const SET_CHILDREN = "CHILDREN/SET_CHILDREN"




